name: Build and run FOLIA

on:
  workflow_dispatch:

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from URL
        run: wget -O app.apk "https://www.dropbox.com/scl/fi/r247jzufh60mosqpkfvj2/app.apk?rlkey=5xbnhybevk4n7m3rd2e7fqgqy&st=5szy2lyf&dl=1"

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: app.apk
